#!/bin/sh

case "$1" in
	start)
		echo "Starting"
		start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
		;;
	stop)
		echo "Stopping"
		start-stop-daemon -K -n aesdsocket
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exti 1
		;;
esac
exit 0
